layout_spectrum: 1
color:
  saturation: 0.7322395
  lightness: 0.2383513
  brandStrength: 0.5448028
  brandColors:
    - '#FFFFFF'
    - '#016D56'
    - '#020203'
    - '#C4C5C8'
    - '#65A294'
  rhythmicContrast: 0.4569893
typography_spectrum: 1
name: www.route66airporttransfers.co.uk
